import Head from 'next/head'
import Card from '../components/Card'
import NavBar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function About() {
    const desc = "Hi, my name is Francisco Molina. I'm 22 years old. I have recently graduated as a Computer Scientist. I enjoy traveling, meeting new people and getting to know new cultures. In my free time I like having drinks at the pub, reading news, talking with friends and playing videogames."
    return (
        <div className={styles.container}>
            <Head>
                <title>About me</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar></NavBar>
            <main className={styles.main}>
                <Card render={true} pathImg={'/me2.jpg'} title={'About me'} txt={desc}></Card>
            </main>
            <footer className={styles.footer}>
                <p>Made with ❤ using NextJS</p>
            </footer>
        </div>
    )
}
